/**
 * Markdown Export Template
 *
 * Generates well-formatted Markdown output for activation plans.
 */

import type { Plan } from '../../../shared/types/plan';

/**
 * Generate a Markdown representation of a plan
 */
export function generateMarkdown(plan: Plan): string {
  const lines: string[] = [];

  // Title
  lines.push(`# ${escapeMarkdown(plan.name)}`);
  lines.push('');

  // Metadata section
  lines.push('## Plan Details');
  lines.push('');
  lines.push(`| Property | Value |`);
  lines.push(`|----------|-------|`);
  lines.push(`| **Park Reference** | ${plan.parkReference} |`);
  lines.push(`| **Activation Date** | ${plan.activationDate} |`);
  lines.push(`| **Time** | ${plan.startTime} - ${plan.endTime} |`);
  lines.push(`| **Status** | ${formatStatus(plan.status)} |`);

  if (plan.operatorCallsign) {
    lines.push(`| **Operator** | ${escapeMarkdown(plan.operatorCallsign)} |`);
  }

  lines.push('');

  // Equipment section
  if (plan.equipmentPreset) {
    lines.push('## Equipment');
    lines.push('');
    lines.push(`| Component | Details |`);
    lines.push(`|-----------|---------|`);
    lines.push(`| **Preset Name** | ${escapeMarkdown(plan.equipmentPreset.name)} |`);
    lines.push(`| **Radio** | ${escapeMarkdown(plan.equipmentPreset.radio)} |`);
    lines.push(`| **Antenna** | ${escapeMarkdown(plan.equipmentPreset.antenna)} |`);
    lines.push(`| **Power** | ${plan.equipmentPreset.powerWatts}W |`);
    lines.push(`| **Mode** | ${escapeMarkdown(plan.equipmentPreset.mode)} |`);

    if (plan.equipmentPreset.notes) {
      lines.push(`| **Notes** | ${escapeMarkdown(plan.equipmentPreset.notes)} |`);
    }

    lines.push('');
  }

  // Bands section
  if (plan.bands.length > 0) {
    lines.push('## Planned Bands');
    lines.push('');
    lines.push(plan.bands.map(band => `- ${band}`).join('\n'));
    lines.push('');
  }

  // Time Slots section
  if (plan.timeSlots.length > 0) {
    lines.push('## Time Slots');
    lines.push('');
    lines.push(`| Time | Band | Mode | Frequency | Notes |`);
    lines.push(`|------|------|------|-----------|-------|`);

    for (const slot of plan.timeSlots) {
      const freq = slot.frequency ? `${slot.frequency} MHz` : '-';
      const notes = slot.notes ? escapeMarkdown(slot.notes) : '-';
      lines.push(`| ${slot.startTime} - ${slot.endTime} | ${slot.band} | ${slot.mode} | ${freq} | ${notes} |`);
    }

    lines.push('');
  }

  // Notes section
  if (plan.notes) {
    lines.push('## Notes');
    lines.push('');
    lines.push(escapeMarkdown(plan.notes));
    lines.push('');
  }

  // Footer
  lines.push('---');
  lines.push('');
  lines.push(`*Generated by POTA Activation Planner*`);
  lines.push(`*Created: ${formatDate(plan.createdAt)}*`);
  lines.push(`*Last Modified: ${formatDate(plan.updatedAt)}*`);

  return lines.join('\n');
}

/**
 * Escape special Markdown characters
 */
function escapeMarkdown(text: string): string {
  return text
    .replace(/\\/g, '\\\\')
    .replace(/\*/g, '\\*')
    .replace(/_/g, '\\_')
    .replace(/`/g, '\\`')
    .replace(/\|/g, '\\|');
}

/**
 * Format plan status for display
 */
function formatStatus(status: string): string {
  const statusMap: Record<string, string> = {
    draft: 'Draft',
    finalized: 'Finalized',
    completed: 'Completed',
    cancelled: 'Cancelled',
  };
  return statusMap[status] ?? status;
}

/**
 * Format ISO date string to readable format
 */
function formatDate(isoDate: string): string {
  try {
    const date = new Date(isoDate);
    return date.toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'long',
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit',
    });
  } catch {
    return isoDate;
  }
}
